[blockchain]
cro_denom = "tcro"
base_denom = "basetcro"
account_address_prefix = "tcro"
account_pubkey_prefix = "tcro"
validator_address_prefix = "tcrocncl"
validator_pubkey_prefix = "tcrocncl"
connode_address_prefix = "tcrocnclcons"
connode_pubkey_prefix = "tcrocnclconspub"

[sync]
# how many sync jobs running in parallel
window_size = 50

[tendermint]
http_rpc_url = "https://testnet-croeseid-1.crypto.com:26657"

[http]
listening_address = "0.0.0.0:8080"

[database]
host = "localhost"
port = 5432
username = "postgres"
# password can only be provided through Environment variable `DB_PASS`
name = "postgres"
schema = "public"
ssl = true

[postgres]
pool_max_conns = 10
pool_min_conns = 0
pool_max_conn_lifetime = "1h"
pool_max_conn_idle_time = "30m"
pool_health_check_interval = "1m"